// <auto-generated />
namespace Student.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ImagesProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagesProp));
        
        string IMigrationMetadata.Id
        {
            get { return "202205261737433_ImagesProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
